const ERROR_CODES = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    MISSING_REQUIRED_PARAM: "MISSING_REQUIRED_PARAM",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
};

module.exports = ERROR_CODES;